80-hotplug-cpu-mem.rules: restrict cpu rule to x86_64
openSUSE/udev-extra-rules pull request #10
Opened 2022-11-04 12:30 UTC by mwilck

This causes undesirable log messages on ppc64le (bsc#1204423).
It has never been requested for any arch, except for x86_64 in
bsc#703100. So activate the rule for x86_64 only.

See also https://github.com/openSUSE/suse-module-tools/pull/67

2022-11-11 16:40 UTC, tblume requested changes

2022-11-11 16:40 UTC, tblume commented on 80-hotplug-cpu-mem.rules
Just a little nitpick.
You could use the udev built-in CONST{arch} instead of calling an external program.
It should be present >=15SP3.
That looks a bit more efficient and elegant, see the udev manpage for details.

2022-11-15 11:42 UTC, mwilck commented on 80-hotplug-cpu-mem.rules
Nice, I'll fix that. Learn something new about udev every day :-)

2022-11-15 14:45 UTC, mwilck commented on 80-hotplug-cpu-mem.rules
Updated, please double-check.

2022-11-15 16:02 UTC, tblume approved these changes
LGTM

2022-11-15 16:04 UTC, merged